from src.modules.app.import_mm import import_marques_modeles, NomMarquesModeles

def test_import_marques_modeles():
    assert import_marques_modeles() == [NomMarquesModeles(marque='ABARTH', modeles=['124', '500', '595', 'punto evo', 'scorpion']),
 NomMarquesModeles(marque='AC', modeles=['aceca', 'cobra']),
 NomMarquesModeles(marque='AIWAYS', modeles=['u5']),
 NomMarquesModeles(marque='AIXAM', modeles=['500', 'city', 'coupe', 'crossline', 'crossover', 'd-truck', 'e city', 'e coupe', 'e-scouty', 'e-truck', 'minauto']),
 NomMarquesModeles(marque='ALFA ROMEO', modeles=['75', '147', '156', '159', '166', '1600', '1750', '2000', '2600', '4c', '8c', 'alfasud', 'alfetta', 'brera', 'giulia', 'giulietta', 'gt', 'gtv', 'mito', 'montreal', 'rz', 'spider', 'stelvio', 'tonale']),
 NomMarquesModeles(marque='ALPINA', modeles=['b11', 'b3', 'b3 s', 'b4', 'b5', 'b7', 'd3', 'd4']),
 NomMarquesModeles(marque='ALPINE', modeles=['a106', 'a110', 'a310', 'a610', 'gta']),
 NomMarquesModeles(marque='AM GENERAL', modeles=['hmmwv']),
 NomMarquesModeles(marque='AMC', modeles=['pacer']),
 NomMarquesModeles(marque='ANAIG', modeles=['light']),
 NomMarquesModeles(marque='ARIEL', modeles=['atom']),
 NomMarquesModeles(marque='ASTON MARTIN', modeles=['cygnet', 'db11', 'db2', 'db7', 'db9', 'dbs', 'dbx', 'rapide', 'v12 speedster', 'v12 vantage', 'v8 vantage', 'valkyrie', 'vanquish', 'vantage', 'vantage gt8', 'virage', 'volante']),
 NomMarquesModeles(marque='AUDI', modeles=['80', '90', '100', 'a1', 'a2', 'a3', 'a4 allroad', 'a4', 'a5', 'a6', 'a6 allroad', 'a7', 'a8', 'coupe', 'e-tron', 'e-tron gt', 'e-tron s sportback', 'e-tron sportback', 'q2', 'q3', 'q4', 'q5', 'q7', 'q8', 'quattro', 'r8', 'rs e-tron gt', 'rs q3', 'rs q8', 'rs2', 'rs3', 'rs4', 'rs5', 'rs6', 'rs7', 's1', 's3', 's4', 's5', 's6', 's7', 's8', 'sq2', 'sq5', 'sq7', 'sq8', 'tt rs', 'tt', 'tts']),
 NomMarquesModeles(marque='AUSTIN HEALEY', modeles=['100', '3000', 'sprite']),
 NomMarquesModeles(marque='AUSTIN', modeles=['1000', '1100', 'mini', 'mini-moke']),
 NomMarquesModeles(marque='AUTOBIANCHI', modeles=['a112', 'bianchina']),
 NomMarquesModeles(marque='BELLIER', modeles=['b8']),
 NomMarquesModeles(marque='BENTLEY', modeles=['arnage', 'azure', 'bentayga', 'brooklands', 'continental', 'eight', 'flying spur', 'gtc', 'mark', 'mulsanne', 's1', 't', 'turbo r']),
 NomMarquesModeles(marque='BMW', modeles=['327', '700', '2000', '2002', '2800', '3.0', 'i3', 'i3s', 'i4', 'i5', 'i7', 'i8', 'ix', 'ix3', 'm1', 'm4', 'serie 1', 'serie 2', 'serie 3', 'serie 3 gt', 'serie 4', 'serie 5', 'serie 5 gt', 'serie 6 gt', 'serie 6', 'serie 7', 'serie 8', 'serie 8 gran coupe', 'x1', 'x2', 'x3', 'x4', 'x5', 'x6', 'x7', 'xm', 'z1', 'z3', 'z4', 'z8']),
 NomMarquesModeles(marque='BOLLORE', modeles=['bluecar', 'bluesummer']),
 NomMarquesModeles(marque='BUGATTI', modeles=['bugatti', 'veyron']),
 NomMarquesModeles(marque='BUICK', modeles=['century', 'riviera', 'roadmaster']),
 NomMarquesModeles(marque='BURSTNER', modeles=['copa c500 bahia']),
 NomMarquesModeles(marque='BYD', modeles=['atto 3', 'han', 'tang']),
 NomMarquesModeles(marque='CADILLAC', modeles=['allante', 'ats', 'coupe eldorado', 'ct6', 'cts-v', 'cts', 'eldorado', 'escalade', 'serie 62', 'seville', 'srx', 'sts', 'xt5']),
 NomMarquesModeles(marque='CAMPAREVE', modeles=['capcoast 130']),
 NomMarquesModeles(marque='CARVER', modeles=['one']),
 NomMarquesModeles(marque='CASALINI', modeles=['550 gransport', '550 granturismo', '550 trofeo', 'm14', 'm20']),
 NomMarquesModeles(marque='CATERHAM', modeles=['seven', 'super seven']),
 NomMarquesModeles(marque='CHALLENGER', modeles=['genesis 47']),
 NomMarquesModeles(marque='CHATENET', modeles=['ch 26', 'ch 40', 'ch 46', 'media', 'speedino']),
 NomMarquesModeles(marque='CHEVROLET', modeles=['3100', 'alero', 'apache', 'aveo', 'bel air', 'c10', 'camaro', 'captiva', 'chevy', 'corvair', 'corvette', 'cruze', 'el camino', 'impala', 'k20 silverado', 'k5 blazer', 'kalos', 'lacetti', 'malibu', 'master deluxe', 'matiz', 'monte carlo', 'orlando', 'silverado', 'spark', 'suburban', 'tahoe', 'trax']),
 NomMarquesModeles(marque='CHRYSLER', modeles=['300 c', '300 windsor', 'crossfire', 'grand voyager', 'imperial', 'pt cruiser', 'sebring', 'viper', 'voyager']),
 NomMarquesModeles(marque='CITROEN', modeles=['2cv', 'ac4', 'acadiane', 'ami', 'ax', 'berlingo', 'bx', 'c-crosser', 'c-elysee', 'c-zero', 'c15', 'c1', 'c25', 'c2', 'c3', 'c3 aircross', 'c3 picasso', 'c3 pluriel', 'c4 aircross', 'c4 cactus', 'c4 picasso', 'c4 spacetourer', 'c4', 'c5 aircross', 'c5 x', 'c5', 'c6', 'c6', 'c8', 'cx', 'd', 'ds3', 'ds4', 'ds5', 'ds', 'dyane', 'e-mehari', 'evasion', 'grand c4 picasso', 'grand c4 spacetourer', 'jumper', 'jumpy', 'mehari', 'nemo', 'picasso', 'saxo', 'sm', 'spacetourer', 'traction', 'type c', 'visa', 'xantia', 'xm', 'xsara', 'zx']),
 NomMarquesModeles(marque='CUPRA', modeles=['ateca', 'born', 'formentor', 'leon']),
 NomMarquesModeles(marque='DACIA', modeles=['dokker', 'duster', 'jogger', 'lodgy', 'logan', 'sandero', 'spring']),
 NomMarquesModeles(marque='DAEWOO', modeles=['kalos']),
 NomMarquesModeles(marque='DAIHATSU', modeles=['copen', 'cuore', 'materia', 'sirion', 'terios', 'trevis']),
 NomMarquesModeles(marque='DALLARA', modeles=['stradale']),
 NomMarquesModeles(marque='DANGEL', modeles=['berlingo', 'partner']),
 NomMarquesModeles(marque='DE LOREAN', modeles=['dmc-12']),
 NomMarquesModeles(marque='DE TOMASO', modeles=['pantera']),
 NomMarquesModeles(marque='DEVINCI', modeles=['db 718', 'db 721']),
 NomMarquesModeles(marque='DFSK', modeles=['ecocity 35']),
 NomMarquesModeles(marque='DODGE', modeles=['avenger', 'caliber', 'challenger', 'charger', 'durango', 'journey', 'nitro', 'ram', 'ram 1500', 'ramcharger', 'royal custom', 'viper']),
 NomMarquesModeles(marque='DONKERVOORT', modeles=['d8', 's8at']),
 NomMarquesModeles(marque='DS', modeles=['ds 3 crossback', 'ds 3', 'ds 4 crossback', 'ds 4', 'ds 5', 'ds 7', 'ds 7 crossback', 'ds 9', 'ds3']),
 NomMarquesModeles(marque='EXCALIBUR', modeles=['phaeton', 'serie 4', 'ssk']),
 NomMarquesModeles(marque='FARDIER LOHR', modeles=['fl']),
 NomMarquesModeles(marque='FERRARI', modeles=['208', '250', '296', '308', '328', '330', '348', '360', '365', '400', '412', '456', '458', '488', '512', '550', '575', '599', '612', '812', '512 bb', '812 gts', 'california', 'dino', 'f12', 'f355', 'f40', 'f430', 'f8 tributo', 'ff', 'gtc4lusso', 'mondial', 'portofino', 'roma', 'sf90 spider', 'sf90 stradale', 'testarossa']),
 NomMarquesModeles(marque='FEST', modeles=['e-box m']),
 NomMarquesModeles(marque='FIAT', modeles=['124', '126', '130', '500', '600', '850', '500 iii', '500 l', '500 x', '500x', 'barchetta', 'bravo', 'coupe', 'croma', 'dino', 'doblo', 'doblo cargo', 'ducato', 'fiorino', 'freemont', 'fullback', 'grande punto', 'idea', 'palio', 'panda', 'punto evo', 'punto', 'qubo', 'ritmo', 'scudo', 'sedici', 'seicento', 'spider', 'stilo', 'talento', 'tipo', 'ulysse', 'uno', 'x1/9']),
 NomMarquesModeles(marque='FISKER', modeles=['karma']),
 NomMarquesModeles(marque='FORD', modeles=['32 roadster', 'a', 'b-max', 'b', 'bronco', 'c-max', 'capri', 'cobra', 'ecosport', 'edge', 'escort', 'explorer', 'f1', 'f100', 'f150', 'f250', 'fairlane', 'fiesta', 'focus c-max', 'focus', 'fusion', 'galaxy', 'grand c-max', 'grand tourneo connect', 'gt', 'gt 40', 'hot rod', 'ka+', 'ka', 'kuga', 'maverick', 'mercury', 'mondeo', 'mustang', 'mustang mach-e', 'probe', 'puma', 'ranger', 's-max', 'sierra', 't', 'thunderbird', 'torino', 'tourneo connect', 'tourneo courier', 'tourneo custom', 'tourneo', 'transit connect', 'transit courier', 'transit custom', 'transit']),
 NomMarquesModeles(marque='FUSO', modeles=['canter']),
 NomMarquesModeles(marque='GAC GONOW', modeles=['gonow']),
 NomMarquesModeles(marque='GLAS', modeles=['1700']),
 NomMarquesModeles(marque='GMC', modeles=['1500', 'c15', 'savana', 'sierra', 'sierra pick-up', 'yukon']),
 NomMarquesModeles(marque='HANROAD', modeles=['trek', 'trek 4', 'trek 5', 'trek 5 +']),
 NomMarquesModeles(marque='HONDA', modeles=['accord', 'civic', 'cr-v', 'cr-z', 'e', 'fr-v', 'hr-v', 'insight', 'jazz', 'legend', 'logo', 'prelude', 's2000', 's800', 'zr-v']),
 NomMarquesModeles(marque='HOTCHKISS', modeles=['411', 'jeep']),
 NomMarquesModeles(marque='HUMMER', modeles=['h1', 'h2', 'h3']),
 NomMarquesModeles(marque='HYMER', modeles=['camperfree s 600']),
 NomMarquesModeles(marque='HYUNDAI', modeles=['accent', 'atos', 'azera', 'bayon', 'coupe', 'galloper', 'genesis', 'getz', 'h1 van', 'i10', 'i20', 'i30', 'i40', 'ioniq 5', 'ioniq 6', 'ioniq', 'ix20', 'ix35', 'ix55', 'kona', 'matrix', 'nexo', 'santa fe', 'satellite', 'sonata', 'staria', 'tucson', 'veloster']),
 NomMarquesModeles(marque='IMF', modeles=['e-pauline']),
 NomMarquesModeles(marque='INEOS', modeles=['grenadier']),
 NomMarquesModeles(marque='INFINITI', modeles=['ex', 'fx', 'g', 'm', 'q30', 'q50', 'q60', 'q70', 'qx30', 'qx50', 'qx56', 'qx70']),
 NomMarquesModeles(marque='INNOCENTI', modeles=['mini']),
 NomMarquesModeles(marque='ISUZU', modeles=['d-max', 'm 21', 'serie n']),
 NomMarquesModeles(marque='IVECO', modeles=['daily', 'daily chassis cab', 'daily van', 'eurocargo', 'minicab', 'stralis']),
 NomMarquesModeles(marque='JAGUAR', modeles=['420', '3.4', '3.8', 'daimler', 'e-pace', 'f-pace', 'f-type', 'i-pace', 'mk ii', 's-type', 'type e', 'x-type', 'xe', 'xf', 'xj', 'xj12', 'xj6', 'xj8', 'xjr', 'xjs-c', 'xjs', 'xk', 'xk8', 'xkr-s', 'xkr']),
 NomMarquesModeles(marque='JDM SIMPA', modeles=['abaca']),
 NomMarquesModeles(marque='JEEP', modeles=['avenger', 'cherokee', 'cj5', 'cj7', 'compass', 'gladiator', 'grand cherokee', 'patriot', 'renegade', 'willys', 'wrangler']),
 NomMarquesModeles(marque='KARMA', modeles=['revero']),
 NomMarquesModeles(marque='KIA', modeles=['carens', 'cee d', 'ceed', 'e-niro', 'e-soul', 'ev6', 'ev9', 'magentis', 'niro', 'opirus', 'optima', 'picanto', 'pro cee d', 'proceed', 'rio', 'sorento', 'soul', 'sportage', 'stinger', 'stonic', 'venga', 'xceed']),
 NomMarquesModeles(marque='KTM', modeles=['x-bow']),
 NomMarquesModeles(marque='LA STRADA', modeles=['avanti']),
 NomMarquesModeles(marque='LADA', modeles=['2104', 'niva']),
 NomMarquesModeles(marque='LAMBORGHINI', modeles=['aventador', 'gallardo', 'huracan', 'lm', 'murcielago', 'urus']),
 NomMarquesModeles(marque='LANCIA', modeles=['appia', 'aurelia', 'beta', 'delta', 'flaminia', 'flavia', 'fulvia', 'musa', 'phedra', 'thema', 'voyager', 'ypsilon']),
 NomMarquesModeles(marque='LAND ROVER', modeles=['defender', 'discovery sport', 'discovery', 'evoque', 'freelander', 'land', 'range rover evoque', 'range rover sport', 'range rover velar', 'range rover']),
 NomMarquesModeles(marque='LEAPMOTOR', modeles=['t03']),
 NomMarquesModeles(marque='LEXUS', modeles=['ct', 'es', 'gs', 'is', 'lc', 'ls', 'nx', 'rc', 'rx', 'rz', 'sc', 'ux']),
 NomMarquesModeles(marque='LIGIER', modeles=['ixo', 'js50', 'js50l', 'js60', 'js', 'myli']),
 NomMarquesModeles(marque='LINCOLN', modeles=['aviator', 'continental', 'mark viii', 'navigator', 'town car']),
 NomMarquesModeles(marque='LOTUS', modeles=['3-eleven', 'elan', 'elise', 'emira', 'esprit', 'europa', 'evora', 'excel', 'exige']),
 NomMarquesModeles(marque='LYNK & CO', modeles=['01']),
 NomMarquesModeles(marque='MAN', modeles=['tge', 'tgm']),
 NomMarquesModeles(marque='MARCOS', modeles=['1800 gt']),
 NomMarquesModeles(marque='MASERATI', modeles=['3200 gt', 'bora', 'coupe', 'ghibli', 'grancabrio', 'gransport', 'granturismo', 'grecale', 'levante', 'mc20', 'mexico', 'mistral', 'quattroporte', 'spyder']),
 NomMarquesModeles(marque='MATRA', modeles=['bagheera', 'murena']),
 NomMarquesModeles(marque='MAYBACH', modeles=['57 berline']),
 NomMarquesModeles(marque='MAZDA', modeles=['2', '3', '5', '6', '323', 'b2500', 'bt-50', 'cx-30', 'cx-3', 'cx-5', 'cx-60', 'cx-7', 'demio', 'mpv', 'mx-30', 'mx5', 'premacy', 'rx-8']),
 NomMarquesModeles(marque='MCLAREN', modeles=['540c', '570gt', '570s', '600 lt', '620r', '650 s', '675 lt', '720s', '765lt', 'artura', 'elva', 'gt', 'mp4-12c', 'senna']),
 NomMarquesModeles(marque='MEGA', modeles=['club', 'multitruck']),
 NomMarquesModeles(marque='MERCEDES-AMG', modeles=['gt']),
 NomMarquesModeles(marque='MERCEDES', modeles=['190', '200', '220', '230', '240', '250', '280', '300', '307', '320', '350', '380', '450', '500', '560', '600', '1017', 'actros', 'antos', 'arocs', 'axor', 'citan', 'cl', 'cla', 'classe a', 'classe b', 'classe c', 'classe clc', 'classe cls', 'classe e', 'classe g', 'classe gl', 'classe glk', 'classe m', 'classe r', 'classe s', 'classe slk', 'classe t', 'classe v', 'classe x', 'clk', 'eqa', 'eqb', 'eqc', 'eqe', 'eqs', 'eqt', 'eqv', 'gla', 'glb', 'glc coupe', 'glc', 'gle coupe', 'gle', 'gls', 'marco polo', 'sl', 'slc', 'slk', 'slr', 'sls', 'sprinter', 'unimog', 'vaneo', 'viano', 'vito']),
 NomMarquesModeles(marque='MERCURY', modeles=['cougar', 'monterey']),
 NomMarquesModeles(marque='MG', modeles=['a', 'b', 'c', 'ehs', 'f', 'marvel r', 'mg ehs', 'mg zs', 'mg4', 'mg5', 'midget', 'tc', 'td', 'tf', 'zt']),
 NomMarquesModeles(marque='MIA ELECTRIC', modeles=['mia']),
 NomMarquesModeles(marque='MICROCAR', modeles=['due', 'flex', 'm.cross', 'm.go', 'm8']),
 NomMarquesModeles(marque='MICRODRIVE', modeles=['lucki', 'start']),
 NomMarquesModeles(marque='MINAUTO', modeles=['eco']),
 NomMarquesModeles(marque='MINI', modeles=['countryman', 'mini', 'mini cabriolet', 'mini clubman', 'mini coupe', 'mini roadster', 'paceman']),
 NomMarquesModeles(marque='MITSUBISHI', modeles=['asx', 'canter', 'colt czc', 'colt', 'eclipse cross', 'eclipse', 'fuso canter', 'galant', 'i-miev', 'l200', 'lancer', 'montero', 'outlander', 'pajero pinin', 'pajero sport', 'pajero', 'space star']),
 NomMarquesModeles(marque='MLT', modeles=['e-story', 'mehari e-story']),
 NomMarquesModeles(marque='MORGAN', modeles=['4/4', 'aero 8', 'plus 4', 'plus 6', 'plus 8', 'plus four', 'plus six', 'roadster v6', 'roadster', 'super 3']),
 NomMarquesModeles(marque='MORRIS', modeles=['1100', '1300', 'mini']),
 NomMarquesModeles(marque='MPM MOTORS', modeles=['erelis']),
 NomMarquesModeles(marque='NASH', modeles=['metropolitan']),
 NomMarquesModeles(marque='NISSAN', modeles=['100 nx', '350z', '370z', 'almera tino', 'almera', 'ariya', 'cabstar', 'evalia', 'gt-r', 'interstar', 'juke', 'leaf', 'maxima', 'micra', 'murano', 'navara', 'note', 'nt400 cabstar', 'nv200', 'nv250', 'nv300', 'nv400', 'pathfinder', 'patrol', 'pick up', 'pixo', 'primastar', 'primera', 'pulsar', 'qashqai +2', 'qashqai', 'sunny', 'terrano', 'townstar', 'x-trail']),
 NomMarquesModeles(marque='NSU', modeles=['prinz sport']),
 NomMarquesModeles(marque='OLDSMOBILE', modeles=['custom cruiser', 'cutlass', 'f-85', 'f85']),
 NomMarquesModeles(marque='OPALE', modeles=['quattro']),
 NomMarquesModeles(marque='OPEL', modeles=['adam', 'agila', 'ampera', 'antara', 'ascona', 'astra', 'cascada', 'combo', 'combo cargo', 'combo life', 'corsa', 'crossland', 'crossland x', 'grandland x', 'grandland', 'gt', 'insignia', 'karl', 'manta', 'meriva', 'mokka x', 'mokka', 'movano', 'omega', 'signum', 'speedster', 'tigra', 'vectra', 'vivaro', 'zafira life', 'zafira tourer', 'zafira']),
 NomMarquesModeles(marque='PACKARD', modeles=['super eight']),
 NomMarquesModeles(marque='PANTHER', modeles=['j72', 'kallista']),
 NomMarquesModeles(marque='PEUGEOT', modeles=['104', '106', '107', '108', '203', '204', '205', '206', '207', '208', '301', '304', '305', '306', '307', '308', '309', '403', '404', '405', '406', '407', '408', '504', '505', '508', '604', '605', '607', '807', '1007', '2008', '3008', '4007', '4008', '5008', '206+', '207+', '508 rxh', 'bipper tepee', 'bipper', 'boxer', 'expert tepee', 'expert', 'ion', 'j5', 'partner', 'partner tepee', 'rcz', 'rifter', 'traveller']),
 NomMarquesModeles(marque='PGO', modeles=['cevennes', 'hemera', 'speedster']),
 NomMarquesModeles(marque='PIAGGIO', modeles=['porter']),
 NomMarquesModeles(marque='PILOTE', modeles=['pacific 62px']),
 NomMarquesModeles(marque='PLYMOUTH', modeles=['prowler']),
 NomMarquesModeles(marque='POLESTAR', modeles=['polestar 2']),
 NomMarquesModeles(marque='PONTIAC', modeles=['chieftain', 'firebird', 'gto', 'trans am']),
 NomMarquesModeles(marque='PORSCHE', modeles=['356', '550', '718', '911', '912', '914', '918', '924', '928', '944', '968', 'boxster', 'carrera gt', 'cayenne', 'cayman', 'macan', 'panamera', 'taycan']),
 NomMarquesModeles(marque='RADICAL', modeles=['sr3']),
 NomMarquesModeles(marque='RAM', modeles=['1500']),
 NomMarquesModeles(marque='RENAULT', modeles=['4cv', 'alaskan', 'arkana', 'austral', 'avantime', 'b90', 'captur', 'clio', 'dauphine', 'espace', 'estafette', 'express van', 'express', 'floride', 'fluence', 'fregate', 'grand espace', 'grand kangoo', 'grand modus', 'grand scenic', 'juvaquatre', 'kadjar', 'kangoo', 'kangoo express', 'kangoo van', 'koleos', 'laguna', 'latitude', 'mascott', 'master', 'maxity', 'megane', 'midlum', 'modus', 'premium', 'r10', 'r11', 'r12', 'r15', 'r16', 'r19', 'r20', 'r21', 'r25', 'r30', 'r4', 'r5', 'r8', 'r9', 'rodeo', 's 170', 'safrane', 'scenic', 'spider', 'super 5', 'talisman', 'trafic', 'twingo', 'twizy', 'vel satis', 'wind', 'zoe']),
 NomMarquesModeles(marque='ROLLS ROYCE', modeles=['corniche', 'cullinan', 'dawn', 'ghost', 'phantom', 'silver cloud', 'silver shadow', 'wraith']),
 NomMarquesModeles(marque='ROVER', modeles=['45', '75', 'mini', 'serie 100', 'serie 200', 'serie 600']),
 NomMarquesModeles(marque='SAAB', modeles=['96', '900', '9-3', '9-5']),
 NomMarquesModeles(marque='SANTANA', modeles=['s300', 's350', 's410', 's413', 'vitara']),
 NomMarquesModeles(marque='SEAT', modeles=['alhambra', 'altea', 'arona', 'ateca', 'cordoba', 'exeo', 'ibiza', 'leon', 'mii', 'tarraco', 'toledo']),
 NomMarquesModeles(marque='SECMA', modeles=['f-16', 'fun extr m']),
 NomMarquesModeles(marque='SERES', modeles=['dfsk ec 35', 'seres 3']),
 NomMarquesModeles(marque='SHELBY', modeles=['cobra daytona']),
 NomMarquesModeles(marque='SIMCA', modeles=['6', '1301']),
 NomMarquesModeles(marque='SKODA', modeles=['citigo', 'enyaq', 'fabia', 'kamiq', 'karoq', 'kodiaq', 'octavia', 'popular', 'rapid', 'roomster', 'scala', 'superb', 'yeti']),
 NomMarquesModeles(marque='SMART', modeles=['#1', 'city', 'crossblade', 'forfour', 'fortwo', 'roadster', 'smart']),
 NomMarquesModeles(marque='SSANGYONG', modeles=['actyon sports', 'actyon', 'korando', 'kyron', 'musso', 'rexton', 'rodius', 'tivoli xlv', 'tivoli']),
 NomMarquesModeles(marque='SUBARU', modeles=['brz', 'forester', 'impreza', 'legacy', 'levorg', 'outback', 'solterra', 'trezia', 'tribeca', 'wrx sti', 'xv']),
 NomMarquesModeles(marque='SUNROLLER', modeles=['m150']),
 NomMarquesModeles(marque='SUZUKI', modeles=['across', 'alto', 'baleno', 'celerio', 'grand vitara', 'ignis', 'jimny', 'kizashi', 'liana', 's-cross', 'samurai', 'splash', 'swace', 'swift', 'sx4', 'sx4 s-cross', 'vitara', 'wagon r+']),
 NomMarquesModeles(marque='TALBOT SIMCA', modeles=['1510']),
 NomMarquesModeles(marque='TESLA', modeles=['model 3', 'model s', 'model x', 'model y']),
 NomMarquesModeles(marque='TOYOTA', modeles=['4runner', 'auris', 'avensis verso', 'avensis', 'aygo x', 'aygo', 'bz4x', 'c-hr', 'camry', 'celica', 'corolla', 'corolla verso', 'dyna', 'fj cruiser', 'gt86', 'highlander', 'hilux', 'iq', 'land cruiser sw', 'land cruiser', 'mirai', 'model f', 'mr', 'paseo', 'previa', 'prius', 'prius+', 'proace city', 'proace city verso', 'proace verso', 'proace', 'rav 4', 'rav4', 'supra', 'tacoma', 'tundra', 'urban cruiser', 'verso-s', 'verso', 'yaris', 'yaris cross', 'yaris verso']),
 NomMarquesModeles(marque='TRABANT', modeles=['601']),
 NomMarquesModeles(marque='TRIUMPH', modeles=['gt6', 'spitfire', 'stag', 'tr 3', 'tr 4', 'tr 5 pi', 'tr 6']),
 NomMarquesModeles(marque='TVR', modeles=['chimaera']),
 NomMarquesModeles(marque='UMM', modeles=['alter']),
 NomMarquesModeles(marque='VANDERHALL', modeles=['carmel']),
 NomMarquesModeles(marque='VOLKSWAGEN', modeles=['1200', '1300', '1303', '1500', '1600', 'amarok', 'arteon', 'bora', 'caddy', 'california', 'caravelle', 'cc', 'coccinelle', 'combi', 'corrado', 'crafter', 'eos', 'fox', 'golf plus', 'golf sportsvan', 'golf', 'grand california', 'id. buzz', 'id.3', 'id.4', 'id.5', 'iltis', 'jetta', 'karman ghia', 'lt combi', 'lt', 'lupo', 'multivan', 'new beetle', 'passat cc', 'passat', 'phaeton', 'polo', 'scirocco', 'sharan', 't-cross', 't-roc', 'taigo', 'tiguan allspace', 'tiguan', 'touareg', 'touran', 'transporter', 'up!', 'up']),
 NomMarquesModeles(marque='VOLVO', modeles=['144', '145', '480', '850', '940', '960', 'c30', 'c40', 'c70', 'pv544', 's40', 's60', 's70', 's80', 's90', 'v40 cross country', 'v40', 'v50', 'v60 cross country', 'v60', 'v70', 'v90 cross country', 'v90', 'xc40', 'xc60', 'xc70', 'xc90']),
 NomMarquesModeles(marque='WESTFIELD', modeles=['fw300']),
 NomMarquesModeles(marque='WIESMANN', modeles=['gt', 'roadster']),
 NomMarquesModeles(marque='WOLSELEY', modeles=['hornet'])]